// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: calculator/calculatorpb/calculate.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//message
type Cal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Intput_1 int32 `protobuf:"varint,1,opt,name=intput_1,json=intput1,proto3" json:"intput_1,omitempty"`
	Intput_2 int32 `protobuf:"varint,2,opt,name=intput_2,json=intput2,proto3" json:"intput_2,omitempty"`
}

func (x *Cal) Reset() {
	*x = Cal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cal) ProtoMessage() {}

func (x *Cal) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cal.ProtoReflect.Descriptor instead.
func (*Cal) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calculate_proto_rawDescGZIP(), []int{0}
}

func (x *Cal) GetIntput_1() int32 {
	if x != nil {
		return x.Intput_1
	}
	return 0
}

func (x *Cal) GetIntput_2() int32 {
	if x != nil {
		return x.Intput_2
	}
	return 0
}

//request
type CalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cal *Cal `protobuf:"bytes,1,opt,name=cal,proto3" json:"cal,omitempty"`
}

func (x *CalRequest) Reset() {
	*x = CalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalRequest) ProtoMessage() {}

func (x *CalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalRequest.ProtoReflect.Descriptor instead.
func (*CalRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calculate_proto_rawDescGZIP(), []int{1}
}

func (x *CalRequest) GetCal() *Cal {
	if x != nil {
		return x.Cal
	}
	return nil
}

//response
type CalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output int32 `protobuf:"varint,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CalResponse) Reset() {
	*x = CalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalResponse) ProtoMessage() {}

func (x *CalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalResponse.ProtoReflect.Descriptor instead.
func (*CalResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calculate_proto_rawDescGZIP(), []int{2}
}

func (x *CalResponse) GetOutput() int32 {
	if x != nil {
		return x.Output
	}
	return 0
}

//CalManyTimesResponse
type CalManyTimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cal *Cal `protobuf:"bytes,1,opt,name=cal,proto3" json:"cal,omitempty"`
}

func (x *CalManyTimesRequest) Reset() {
	*x = CalManyTimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalManyTimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalManyTimesRequest) ProtoMessage() {}

func (x *CalManyTimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalManyTimesRequest.ProtoReflect.Descriptor instead.
func (*CalManyTimesRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calculate_proto_rawDescGZIP(), []int{3}
}

func (x *CalManyTimesRequest) GetCal() *Cal {
	if x != nil {
		return x.Cal
	}
	return nil
}

//CalManyTimesResponse
type CalManyTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output int32 `protobuf:"varint,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CalManyTimesResponse) Reset() {
	*x = CalManyTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalManyTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalManyTimesResponse) ProtoMessage() {}

func (x *CalManyTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculatorpb_calculate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalManyTimesResponse.ProtoReflect.Descriptor instead.
func (*CalManyTimesResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calculatorpb_calculate_proto_rawDescGZIP(), []int{4}
}

func (x *CalManyTimesResponse) GetOutput() int32 {
	if x != nil {
		return x.Output
	}
	return 0
}

var File_calculator_calculatorpb_calculate_proto protoreflect.FileDescriptor

var file_calculator_calculatorpb_calculate_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x03, 0x43, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x69, 0x6e, 0x74, 0x70, 0x75, 0x74, 0x31, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x70, 0x75,
	0x74, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x70, 0x75,
	0x74, 0x32, 0x22, 0x2f, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x03, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x52, 0x03,
	0x63, 0x61, 0x6c, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x38, 0x0a, 0x13, 0x43, 0x61,
	0x6c, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x03, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x52,
	0x03, 0x63, 0x61, 0x6c, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x4d, 0x61, 0x6e, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x32, 0xa9, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x12, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x4d, 0x61, 0x6e, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_calculatorpb_calculate_proto_rawDescOnce sync.Once
	file_calculator_calculatorpb_calculate_proto_rawDescData = file_calculator_calculatorpb_calculate_proto_rawDesc
)

func file_calculator_calculatorpb_calculate_proto_rawDescGZIP() []byte {
	file_calculator_calculatorpb_calculate_proto_rawDescOnce.Do(func() {
		file_calculator_calculatorpb_calculate_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_calculatorpb_calculate_proto_rawDescData)
	})
	return file_calculator_calculatorpb_calculate_proto_rawDescData
}

var file_calculator_calculatorpb_calculate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_calculator_calculatorpb_calculate_proto_goTypes = []interface{}{
	(*Cal)(nil),                  // 0: calculator.Cal
	(*CalRequest)(nil),           // 1: calculator.CalRequest
	(*CalResponse)(nil),          // 2: calculator.CalResponse
	(*CalManyTimesRequest)(nil),  // 3: calculator.CalManyTimesRequest
	(*CalManyTimesResponse)(nil), // 4: calculator.CalManyTimesResponse
}
var file_calculator_calculatorpb_calculate_proto_depIdxs = []int32{
	0, // 0: calculator.CalRequest.cal:type_name -> calculator.Cal
	0, // 1: calculator.CalManyTimesRequest.cal:type_name -> calculator.Cal
	1, // 2: calculator.CalService.calculate:input_type -> calculator.CalRequest
	3, // 3: calculator.CalService.calculateManyTimes:input_type -> calculator.CalManyTimesRequest
	2, // 4: calculator.CalService.calculate:output_type -> calculator.CalResponse
	4, // 5: calculator.CalService.calculateManyTimes:output_type -> calculator.CalManyTimesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_calculator_calculatorpb_calculate_proto_init() }
func file_calculator_calculatorpb_calculate_proto_init() {
	if File_calculator_calculatorpb_calculate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_calculatorpb_calculate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calculate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calculate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calculate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalManyTimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calculatorpb_calculate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalManyTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_calculatorpb_calculate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_calculatorpb_calculate_proto_goTypes,
		DependencyIndexes: file_calculator_calculatorpb_calculate_proto_depIdxs,
		MessageInfos:      file_calculator_calculatorpb_calculate_proto_msgTypes,
	}.Build()
	File_calculator_calculatorpb_calculate_proto = out.File
	file_calculator_calculatorpb_calculate_proto_rawDesc = nil
	file_calculator_calculatorpb_calculate_proto_goTypes = nil
	file_calculator_calculatorpb_calculate_proto_depIdxs = nil
}
